RusLocale = {
  ru_en = {
    vim.api.nvim_set_keymap("", "й", "q", {}),
    vim.api.nvim_set_keymap("", "ц", "w", {}),
    vim.api.nvim_set_keymap("", "у", "e", {}),
    vim.api.nvim_set_keymap("", "к", "r", {}),
    vim.api.nvim_set_keymap("", "е", "t", {}),
    vim.api.nvim_set_keymap("", "н", "y", {}),
    vim.api.nvim_set_keymap("", "г", "u", {}),
    vim.api.nvim_set_keymap("", "ш", "i", {}),
    vim.api.nvim_set_keymap("", "щ", "o", {}),
    vim.api.nvim_set_keymap("", "з", "p", {}),
    vim.api.nvim_set_keymap("", "х", "[", {}),
    vim.api.nvim_set_keymap("", "ъ", "]", {}),

    vim.api.nvim_set_keymap("", "ф", "a", {}),
    vim.api.nvim_set_keymap("", "ы", "s", {}),
    vim.api.nvim_set_keymap("", "в", "d", {}),
    vim.api.nvim_set_keymap("", "а", "f", {}),
    vim.api.nvim_set_keymap("", "п", "g", {}),
    vim.api.nvim_set_keymap("", "р", "h", {}),
    vim.api.nvim_set_keymap("", "о", "j", {}),
    vim.api.nvim_set_keymap("", "л", "k", {}),
    vim.api.nvim_set_keymap("", "д", "l", {}),
    vim.api.nvim_set_keymap("", "ж", ";", {}),
    vim.api.nvim_set_keymap("", "э", "'", {}),

    vim.api.nvim_set_keymap("", "я", "z", {}),
    vim.api.nvim_set_keymap("", "ч", "x", {}),
    vim.api.nvim_set_keymap("", "с", "c", {}),
    vim.api.nvim_set_keymap("", "м", "v", {}),
    vim.api.nvim_set_keymap("", "и", "b", {}),
    vim.api.nvim_set_keymap("", "т", "n", {}),
    vim.api.nvim_set_keymap("", "ь", "m", {}),
    vim.api.nvim_set_keymap("", "б", ",", {}),
    vim.api.nvim_set_keymap("", "ю", "/", {}),

    vim.api.nvim_set_keymap("", "Й", "Q", {}),
    vim.api.nvim_set_keymap("", "Ц", "W", {}),
    vim.api.nvim_set_keymap("", "У", "E", {}),
    vim.api.nvim_set_keymap("", "К", "R", {}),
    vim.api.nvim_set_keymap("", "Е", "T", {}),
    vim.api.nvim_set_keymap("", "Н", "Y", {}),
    vim.api.nvim_set_keymap("", "Г", "U", {}),
    vim.api.nvim_set_keymap("", "Ш", "I", {}),
    vim.api.nvim_set_keymap("", "Щ", "O", {}),
    vim.api.nvim_set_keymap("", "З", "P", {}),
    vim.api.nvim_set_keymap("", "Х", "[", {}),
    vim.api.nvim_set_keymap("", "Ъ", "]", {}),

    vim.api.nvim_set_keymap("", "Ф", "A", {}),
    vim.api.nvim_set_keymap("", "Ы", "S", {}),
    vim.api.nvim_set_keymap("", "В", "D", {}),
    vim.api.nvim_set_keymap("", "А", "F", {}),
    vim.api.nvim_set_keymap("", "П", "G", {}),
    vim.api.nvim_set_keymap("", "Р", "H", {}),
    vim.api.nvim_set_keymap("", "О", "J", {}),
    vim.api.nvim_set_keymap("", "Л", "K", {}),
    vim.api.nvim_set_keymap("", "Д", "L", {}),
    vim.api.nvim_set_keymap("", "Ж", ":", {}),
    vim.api.nvim_set_keymap("", "Э", "'", {}),

    vim.api.nvim_set_keymap("", "Я", "Z", {}),
    vim.api.nvim_set_keymap("", "Ч", "X", {}),
    vim.api.nvim_set_keymap("", "С", "C", {}),
    vim.api.nvim_set_keymap("", "М", "V", {}),
    vim.api.nvim_set_keymap("", "И", "B", {}),
    vim.api.nvim_set_keymap("", "Т", "N", {}),
    vim.api.nvim_set_keymap("", "Ь", "M", {}),
    vim.api.nvim_set_keymap("", "Б", ",", {}),
    vim.api.nvim_set_keymap("", "Ю", "/", {}),
  },
}
